Add get and create shop endpoints
SkouRene/HL-phpclient pull request #19
Opened 2017-03-11 15:25 UTC by borch-inc

- Added getting list shops
- Added creating shops on list.

Used on Hli for DdD integrations.

2017-03-12 16:10 UTC, korshoj reviewed
Looks fine. Only since this is generally available please do not write anything internal in comments /messages. Also could you please add an Example or two that displays how to use this (specifically createShop is impossible to guess how to use from this code)

2017-03-13 07:09 UTC, korshoj approved these changes

2017-03-13 07:17 UTC, makazetenshi requested changes

2017-03-13 07:17 UTC, makazetenshi commented on src/Examples/ShopExamples.php
> +var_dump($webhookService->getshopss($listId));
I think you misspelled the getshops method since it has two s's ?

2017-03-13 07:28 UTC, merged